"use client";
import { useState } from "react";
import Image from "next/image";

const Arrow = () => <svg viewBox="0 0 20 20" className="h-4 w-4 fill-none stroke-current stroke-2"><path d="M3 10h13M11 5l5 5-5 5" /></svg>;
const Icon = ({ type = "pulse" }) => <svg viewBox="0 0 24 24" className="h-5 w-5 fill-none stroke-current stroke-[1.8]">{type === "pulse" ? <path d="M3 12h4l2-5 4 10 2-5h6" /> : type === "bell" ? <path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4" /> : type === "device" ? <><rect x="6" y="3" width="12" height="18" rx="2" /><path d="M10 17h4M9 7h6" /></> : <><circle cx="12" cy="8" r="4" /><path d="M4 21c.8-4 3.5-6 8-6s7.2 2 8 6" /></>}</svg>;
function Brand({ dark = false }) { return <a href="#home" className={`flex items-center gap-2.5 font-semibold tracking-tight ${dark ? "text-white" : "text-[#183d2c]"}`}><span className="grid h-8 w-8 place-items-center rounded-[10px] bg-[#216644] text-white"><svg viewBox="0 0 28 28" className="h-5 w-5 fill-none stroke-current stroke-2"><path d="M5 18c1-6 5-9 10-9 4 0 7 3 8 7-3 1-5 1-7 0-1.5 3-5 5-9 4M6 13 3 10M20 10l4-3" /></svg></span>PashuRaksha</a> }
function Navbar() { const [open, setOpen] = useState(false); const links = ["Home", "About", "How It Works", "Features", "Contact"]; return <header className="sticky top-0 z-30 border-b border-[#dce6dc] bg-[#f8faf6]/95 backdrop-blur"><nav className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 lg:px-8"><Brand /><div className="hidden gap-7 text-sm text-[#53675b] md:flex">{links.map(x => <a key={x} href={"#" + x.toLowerCase().replaceAll(" ", "-")} className="hover:text-[#216644]">{x}</a>)}</div><div className="hidden items-center gap-5 md:flex"><a href="/login" className="text-sm font-medium text-[#315946]">Login</a><a href="/signup" className="rounded-lg bg-[#216644] px-4 py-2.5 text-sm font-medium text-white">Get Started</a></div><button onClick={() => setOpen(!open)} className="p-2 md:hidden" aria-label="Toggle navigation"><svg viewBox="0 0 24 24" className="h-6 w-6 fill-none stroke-current stroke-2"><path d={open ? "M5 5l14 14M19 5 5 19" : "M4 7h16M4 12h16M4 17h16"} /></svg></button></nav>{open && <div className="border-t border-[#dce6dc] px-5 pb-5 md:hidden">{links.map(x => <a onClick={() => setOpen(false)} key={x} href={"#" + x.toLowerCase().replaceAll(" ", "-")} className="block border-b border-[#e5ece4] py-3 text-sm">{x}</a>)}<a href="/signup" className="mt-4 block rounded-lg bg-[#216644] py-3 text-center text-sm font-medium text-white">Get Started</a></div>}</header> }
function Visual() {
  return (
    <div className="relative mx-auto h-[360px] w-full max-w-[570px] overflow-hidden rounded-2xl border border-[#d7e4d5] bg-[#e7f0e3] shadow-[0_18px_45px_rgba(29,67,43,.12)]">
      <Image
        src="/hero-cow.svg"
        alt="Illustration of a healthy Holstein cow wearing a connected health-monitoring sensor in a green pasture"
        fill
        priority
        sizes="(max-width: 1024px) 100vw, 570px"
        className="object-cover"
      />
      <div className="absolute left-5 top-5 rounded-lg bg-white/95 px-3 py-2 shadow-sm">
        <p className="text-[10px] uppercase tracking-wider text-[#68786a]">Connected herd</p>
        <p className="text-sm font-semibold">12 animals online</p>
      </div>
      <div className="absolute right-4 top-6 rounded-lg bg-white/95 p-3 shadow-sm">
        <div className="flex items-center gap-2 text-xs font-medium text-[#315946]"><span className="text-[#24734a]"><Icon /></span>Stable readings</div>
        <div className="mt-2 flex gap-1"><i className="h-1.5 w-7 rounded bg-[#72a86d]" /><i className="h-1.5 w-5 rounded bg-[#72a86d]" /><i className="h-1.5 w-3 rounded bg-[#bad5b4]" /></div>
      </div>
      <div className="absolute bottom-8 right-3 w-40 rounded-lg bg-white/95 p-3 shadow-md">
        <div className="flex justify-between text-[10px]"><span>Cow1 · #021</span><span className="text-[#277046]">Healthy</span></div>
        <div className="mt-3 flex h-9 items-end gap-1">{[15, 27, 20, 35, 23, 30].map((n, i) => <i key={i} className="w-1.5 rounded-t bg-[#6fa86d]" style={{ height: n }} />)}</div>
        <p className="mt-2 text-[10px] text-[#4f6655]">Activity within usual range</p>
      </div>
    </div>
  );
}
function Hero() { return <section id="home" className="bg-[#f8faf6]"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-14 lg:grid-cols-[.92fr_1.08fr] lg:px-8 lg:py-20"><div className="max-w-xl"><p className="mb-5 flex items-center gap-2 text-[11px] font-semibold tracking-[.16em] text-[#34704c]"><i className="h-px w-7 bg-[#74a679]" />SMART LIVESTOCK HEALTH MONITORING</p><h1 className="text-4xl font-semibold leading-[1.12] tracking-[-.045em] text-[#183d2c] sm:text-5xl">Better care for every animal.</h1><p className="mt-5 max-w-lg text-base leading-7 text-[#53675b]">PashuRaksha brings connected cattle monitoring and simple digital tools together, helping farmers notice meaningful changes and take timely action.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#features" className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#216644] px-5 py-3 text-sm font-medium text-white">Explore PashuRaksha <Arrow /></a><a href="#how-it-works" className="inline-flex items-center justify-center gap-2 rounded-lg border border-[#cbdac9] px-5 py-3 text-sm font-medium text-[#315946]">How it works</a></div><p className="mt-7 text-xs text-[#6d7d70]">✓ Built for day-to-day farm decisions</p></div><Visual /></div></section> }
function Intro() { return <section id="about" className="border-y border-[#e2e9df] bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-16 lg:grid-cols-[.8fr_1.2fr] lg:px-8 lg:py-20"><p className="text-sm font-medium text-[#3f7650]">Why PashuRaksha</p><div><h2 className="text-3xl font-semibold tracking-[-.035em]">Technology that helps farmers care better.</h2><p className="mt-5 max-w-2xl leading-7 text-[#5c6d61]">Farmers often depend on visual observation and manual checks to understand cattle health. PashuRaksha is designed to make that routine easier, bringing useful information into one clear, practical platform.</p></div></div></section> }
function Workflow() { let steps = [["01", "Monitor", "Connected devices collect relevant health and activity information."], ["02", "Connect", "Readings are transferred to the PashuRaksha platform."], ["03", "Understand", "Simple views show patterns and animal health status."], ["04", "Act", "Changes that need attention are easier to spot and respond to."]]; return <section id="how-it-works" className="bg-[#f2f6ef]"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-20"><p className="text-sm font-medium text-[#3f7650]">A simple, connected workflow</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.035em]">From the shed to a clearer picture.</h2><div className="mt-12 grid gap-7 sm:grid-cols-2 lg:grid-cols-4">{steps.map(([n, t, c]) => <div key={t} className="border-t border-[#bdd1bb] pt-5"><p className="text-xs font-semibold tracking-widest text-[#57905f]">{n}</p><h3 className="mt-4 text-lg font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-[#5d6d60]">{c}</p></div>)}</div></div></section> }
function Features() { let items = [["pulse", "Cattle health monitoring", "Keep health-related readings in one dependable view."], ["profile", "Individual animal profiles", "Maintain a useful record for every animal."], ["bell", "Health alerts", "Surface unusual changes and important events."], ["device", "IoT connectivity", "Bring compatible monitoring devices into the platform."], ["pulse", "Health history", "Review past readings and health trends."], ["profile", "Farmer-friendly interface", "See what matters without unnecessary complexity."]]; return <section id="features" className="bg-white"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-20"><p className="text-sm font-medium text-[#3f7650]">Made for practical care</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.035em]">Essential tools, kept straightforward.</h2><div className="mt-10 grid border-l border-t border-[#dfe8dd] sm:grid-cols-2 lg:grid-cols-3">{items.map(([i, t, c]) => <article key={t} className="border-b border-r border-[#dfe8dd] p-6 lg:p-7"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#e9f2e7] text-[#35754c]"><Icon type={i} /></span><h3 className="mt-5 font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-[#617166]">{c}</p></article>)}</div></div></section> }
function Dashboard() { let stats = [["24", "Total cattle", "#dfece0"], ["20", "Healthy", "#cde8cf"], ["03", "Needs attention", "#f5e5bd"], ["01", "Offline device", "#e7e5e0"]]; return <section className="bg-[#203e2e] py-16 lg:py-20"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[.7fr_1.3fr] lg:px-8 lg:items-center"><div><p className="text-sm font-medium text-[#acd19e]">A clear daily overview</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.035em] text-white">See the herd at a glance.</h2><p className="mt-5 leading-7 text-[#d2dfd0]">The future PashuRaksha dashboard keeps animal status, recent readings, and attention items close at hand.</p><p className="mt-6 text-xs text-[#a8bda9]">Illustrative product preview — static demo data</p></div><div className="rounded-xl bg-[#f8faf6] p-4 shadow-2xl sm:p-5"><div className="flex justify-between border-b border-[#e2e9df] pb-4"><div><p className="text-xs text-[#718073]">Good morning, Ramesh</p><h3 className="mt-1 text-sm font-semibold">Herd overview</h3></div><span className="rounded-md bg-[#e7f2e5] px-2.5 py-1 text-[10px] text-[#347247]">Demo farm</span></div><div className="grid grid-cols-2 gap-2 py-4 sm:grid-cols-4">{stats.map(([n, l, b]) => <div key={l} className="rounded-lg p-3" style={{ backgroundColor: b }}><p className="text-xl font-semibold">{n}</p><p className="mt-1 text-[10px] text-[#5d6d61]">{l}</p></div>)}</div><div className="grid gap-3 md:grid-cols-[1.1fr_.9fr]"><div className="rounded-lg border border-[#e0e8de] p-4"><div className="flex justify-between text-xs"><b>Activity over 7 days</b><span className="text-[#718073]">Herd average</span></div><div className="mt-6 flex h-24 items-end justify-between gap-2">{[35, 52, 44, 68, 55, 82, 64].map((v, i) => <div key={i} className="flex h-full flex-1 items-end"><i className="w-full rounded-t bg-[#74a96d]" style={{ height: v + "%" }} /></div>)}</div></div><div className="rounded-lg border border-[#e0e8de] p-4"><p className="text-xs font-medium">Recent attention</p><div className="mt-3 space-y-3 text-[10px]"><p><b>Gauri #021</b><br /><span className="text-[#728072]">Temperature slightly elevated · Review</span></p><p><b>Nandi #014</b><br /><span className="text-[#728072]">Activity lower than usual · Check</span></p></div></div></div></div></div></section> }
function Info() { return <><section className="bg-[#f8faf6]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-2 lg:px-8 lg:py-20"><div><p className="text-sm font-medium text-[#3f7650]">Farmer-first by design</p><h2 className="mt-3 max-w-md text-3xl font-semibold tracking-[-.035em]">Designed for the people who care for them every day.</h2></div><div><p className="leading-7 text-[#5c6d61]">Not every farm needs more software. It needs the right information, presented clearly, when it is useful. PashuRaksha is built around simple status indicators and views that work on a phone or at a desk.</p><div className="mt-7 grid gap-4 sm:grid-cols-3">{["Easy to understand", "Important status, visible quickly", "Clear on any screen"].map(t => <div key={t} className="border-l-2 border-[#85ae7d] pl-3 text-sm font-medium text-[#315946]">{t}</div>)}</div></div></div></section><section className="border-y border-[#e0e8de] bg-white"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-20"><p className="text-sm font-medium text-[#3f7650]">Connected, without the complexity</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.035em]">The technology stays in the background.</h2><p className="mt-4 max-w-xl leading-7 text-[#5c6d61]">Connected devices collect data. The platform organizes it. Farmers see what matters.</p><div className="mt-10 grid gap-5 sm:grid-cols-4">{["IoT devices", "Data collection", "PashuRaksha platform", "Monitoring interface"].map((x, i) => <div key={x} className="flex items-center gap-3"><b className="grid h-10 w-10 place-items-center rounded-full border border-[#bed3b9] text-xs text-[#44804e]">0{i + 1}</b><span className="text-sm font-medium text-[#315946]">{x}</span></div>)}</div></div></section></> }
function Footer() { return <><section id="contact" className="bg-[#dcebd7]"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-14 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div><h2 className="text-3xl font-semibold tracking-[-.035em]">Smarter monitoring. Better care.</h2><p className="mt-3 text-[#526b57]">Bring cattle monitoring, health information, and timely alerts together.</p></div><a href="mailto:hello@pashuraksha.in" className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#216644] px-5 py-3 text-sm font-medium text-white">Get Started <Arrow /></a></div></section><footer className="bg-[#183d2c] text-[#ceddcf]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-12 sm:grid-cols-2 lg:grid-cols-[1.5fr_1fr_1fr] lg:px-8"><div><Brand /><p className="mt-4 max-w-sm text-sm leading-6 text-[#b1c4b3]">A practical platform for connected cattle health monitoring and better day-to-day care.</p></div><div><p className="text-xs font-semibold uppercase tracking-wider text-[#e3eee3]">Explore</p><div className="mt-4 space-y-2 text-sm text-[#b1c4b3]"><a href="#about" className="block">About</a><a href="#how-it-works" className="block">How it works</a><a href="#features" className="block">Features</a></div></div><div><p className="text-xs font-semibold uppercase tracking-wider text-[#e3eee3]">Contact</p><div className="mt-4 space-y-2 text-sm text-[#b1c4b3]"><a href="mailto:hello@pashuraksha.in" className="block">hello@pashuraksha.in</a><a href="https://github.com" className="block">GitHub project</a></div></div></div><div className="border-t border-white/10 px-5 py-5 text-center text-xs text-[#9ab09e]">© 2026 PashuRaksha. Built with care for livestock owners.</div></footer></> }
export default function Home() { return <><Navbar /><main><Hero /><Intro /><Workflow /><Features /><Dashboard /><Info /></main><Footer /></> }
